import {poseAt,joint} from './motion.js';
import {Game,CONFIG,fresh} from './game.js';
const $=id=>document.getElementById(id),ctx=$('canvas').getContext('2d'),KEY='marutto-fighter-v1';
let game=null,paused=false,speed=1,particles=[],effects=[],ghosts=[],lastGhost=-1,hitstop=0,shake=0,last=0,shown='',toastTime=0,saved=null,storageOK=true;
try{saved=JSON.parse(localStorage.getItem(KEY));if(saved&&!(saved.version===1&&['battle','upgrade'].includes(saved.phase)&&Number.isInteger(saved.wave)&&saved.wave>=0&&saved.wave<3&&Number.isFinite(saved.hp)&&saved.hp>0&&saved.hp<=100&&Number.isFinite(saved.gauge)&&saved.gauge>=0&&saved.gauge<=100&&saved.skills?.punch&&Object.keys(saved.skills).every(k=>CONFIG.skills[k]&&Number.isInteger(saved.skills[k])&&saved.skills[k]>0)&&Array.isArray(saved.choices)))saved=null;}catch{saved=null;}
function save(){try{if(['battle','upgrade'].includes(game.run.phase)){saved=structuredClone(game.run);localStorage.setItem(KEY,JSON.stringify(saved));}else{saved=null;localStorage.removeItem(KEY);}}catch{storageOK=false;notice('このブラウザでは保存できません');}}
function notice(text){$('toast').textContent=text;toastTime=2;}
const descriptions={punch:'連撃ダメージが40%アップ',upper:'敵を打ち上げる。ゴーレムには耐性あり',gun:'浮いた敵へ自動追撃。アッパーと連携',spin:'敵が2体以上近づくと範囲攻撃',hammer:'ゲージ満タンで広範囲へ大打撃'};
function title(){shown='title';$('overlay').innerHTML='<div class="panel"><p class="eyebrow">A LITTLE HERO, A BIG ADVENTURE</p><h1>まるっとファイター</h1><p>小さな体で、森いっぱいの敵に挑む。<br>戦いは自動。あなたが選ぶのは、次の強さ。</p><div class="actions"><button class="primary" id="new">新しく挑戦</button>'+(saved?'<button id="resume">つづきから</button>':'')+'</div><p style="font-size:12px">全3戦 / 仮素材の試作版 / 横画面がおすすめ</p></div>';$('new').onclick=()=>start(fresh());if(saved)$('resume').onclick=()=>start(saved);}
function start(run){game=new Game(run);particles=[];effects=[];ghosts=[];lastGhost=-1;hitstop=0;shake=0;paused=false;shown='';save();ui();}
function ui(){if(!game)return;const r=game.run;$('status').hidden=false;$('pause').hidden=r.phase!=='battle';$('pause').textContent=paused?'再開':'一時停止';$('wave').textContent=`第 ${r.wave+1} 戦 / 3`;$('hp').textContent=Math.ceil(r.hp);$('hpFill').style.width=r.hp+'%';$('remaining').textContent=`敵 ${game.enemies.filter(e=>!e.dead).length} 体`;$('gauge').textContent=Math.floor(r.gauge);$('gaugeFill').style.width=r.gauge+'%';$('hint').textContent=!storageOK?'保存不可：この画面を開いたまま遊んでください':r.phase==='battle'?'戦闘は自動。赤い予兆は敵の攻撃。':'強化を選んで次の戦闘へ';
 $('skills').innerHTML=Object.entries(CONFIG.skills).map(([id,s])=>`<div class="skill ${r.skills[id]?'':'locked'}"><b>${s.icon}</b>${s.name}<small>${r.skills[id]?`Lv.${r.skills[id]} · ${game.cooldowns[id]>0?game.cooldowns[id].toFixed(1)+'秒':'準備OK'}`:'未習得'}</small></div>`).join('');
 const phase=paused?'pause':r.phase;if(phase===shown)return;shown=phase;
 if(phase==='battle')$('overlay').innerHTML='';
 else if(phase==='pause'){$('overlay').innerHTML='<div class="panel"><h2>ひとやすみ</h2><p>戦闘は停止しています。</p><button class="primary" id="continue">再開する</button></div>';$('continue').onclick=()=>{paused=false;ui();};}
 else if(phase==='upgrade'){$('overlay').innerHTML='<div class="panel"><p class="eyebrow">BATTLE COMPLETE</p><h2>次の強さを選ぼう</h2><p>HPを20回復しました。1つ選んで次の戦闘へ。</p><div class="choices">'+r.choices.map((c,i)=>`<button class="choice" data-choice="${i}"><span>${CONFIG.skills[c.id].icon}</span><strong>${CONFIG.skills[c.id].name}${c.upgrade?'＋':''}</strong><small>${c.upgrade?'ダメージが40%分アップ':descriptions[c.id]}</small></button>`).join('')+'</div></div>';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(game.choose(Number(b.dataset.choice))){particles=[];effects=[];ghosts=[];lastGhost=-1;hitstop=0;shake=0;save();ui();}});}
 else{$('overlay').innerHTML=`<div class="panel"><p class="eyebrow">${phase==='clear'?'FOREST CLEARED':'TRY AGAIN'}</p><h1>${phase==='clear'?'森のチャンピオン！':'また挑戦しよう'}</h1><p>${phase==='clear'?'全3戦クリア！小さな英雄の大きな勝利。':`第${r.wave+1}戦で力尽きました。強化を変えて再挑戦。`}</p><button class="primary" id="retry">もう一度挑戦</button></div>`;$('retry').onclick=()=>start(fresh());}}
$('pause').onclick=()=>{paused=!paused;ui();};$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`速度 ×${speed}`;};document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.run.phase==='battle'){paused=true;ui();}});
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function line(x,y,x2,y2,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function limb(a,b,color,width,bend){const middle=joint(a,b,Math.hypot(b[0]-a[0],b[1]-a[1])*.55,bend);line(...a,...middle,color,width);line(...middle,...b,color,width);}
function hero(h){const p=poseAt(h);ctx.save();ctx.translate(h.renderX??h.x,255);ellipse(0,7,24,5,'#223f4033');ctx.scale(h.face*(Math.abs(p.turn)<.15?.15:p.turn),1);
 limb(p.hip,p.leftFoot,'#d4e0dd',10,1);limb(p.chest,p.leftHand,'#d4e0dd',9,1);
 line(...p.hip,...p.chest,'#fff',15);limb(p.hip,p.rightFoot,'#fff',11,-1);limb(p.chest,p.rightHand,'#fff',10,-1);const shade=ctx.createRadialGradient(p.head[0]-6,p.head[1]-8,2,...p.head,22);shade.addColorStop(0,'#ffffff');shade.addColorStop(1,'#c5d9d3');ellipse(...p.head,18,19,shade);
 if(h.pose==='hammer'&&h.poseTime>0){const angle=p.hammerAngle;const hand=p.rightHand;const end=[hand[0]+Math.sin(angle)*57,hand[1]-Math.cos(angle)*57];line(...hand,...end,'#c89858',6);ctx.save();ctx.translate(...end);ctx.rotate(angle);ctx.fillStyle='#ffe29d';ctx.fillRect(-27,-14,54,28);ctx.strokeStyle='#ae8047';ctx.lineWidth=3;ctx.strokeRect(-27,-14,54,28);ctx.restore();}ctx.restore();}
function enemy(e,t){const y=255-e.y,s=e.size;ctx.save();ctx.globalAlpha=e.dead?Math.min(1,e.deathTime/.3):1;ellipse(e.x,262,s*.85,5,'#1b3e3833');ctx.save();ctx.translate(e.x,y);const stride=e.stride||0,moving=Math.min(1,Math.abs(e.motion||0)/40),step=Math.sin(stride)*moving;ctx.scale((game&&e.x>game.hero.x?-1:1)*(e.type==='boar'?-1:1),1);ctx.rotate(e.dead?(1-e.deathTime/.65)*1.5:(e.hurt||0)*1.1+(e.y>0?e.vx*.001:0));if(e.type==='slime'){const squash=(e.windup>0?.16:0)+(e.landing||0)*.7;ctx.scale(1+squash,1-squash);ctx.translate(0,-Math.abs(Math.sin(stride))*8*moving);}else{ctx.translate(0,-Math.abs(step)*(e.type==='golem'?2:4));ctx.rotate(e.windup>0?-.12:step*.025);}if(e.windup>0){ctx.strokeStyle='#ff7167';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-s, s+9,0,Math.PI*2);ctx.stroke();}if(e.type==='slime'){ellipse(0,-s*.65,s,s*.7+Math.sin(t*5)*3,e.color);}else if(e.type==='boar'){ellipse(0,-s*.55,s+5,s*.65,e.color);ellipse(-s*.7,-s*.5,13,10,'#ddb199');line(-12,-7,-12+step*9,1-Math.max(0,step)*6,'#765c51',8);line(15,-7,15-step*9,1-Math.max(0,-step)*6,'#765c51',8);line(-s,-s*.4,-s-7,-s*.8,'#fff5ce',4);}else if(e.type==='golem'){ctx.fillStyle=e.color;ctx.fillRect(-s*.65,-s*1.35,s*1.3,s);ctx.fillStyle='#c2cbd1';ctx.fillRect(-s*.45,-s*1.95,s*.9,s*.65);line(-s*.7,-s,-s,-s*.35,e.color,18);line(s*.7,-s,s+(e.strike>0?16:0),-s*.35-(e.strike>0?20:0),e.color,18);line(-16,-20,-19+step*8,-Math.max(0,step)*5,'#798998',17);line(16,-20,19-step*8,-Math.max(0,-step)*5,'#798998',17);}else{line(-8,-16,-12+step*11,-Math.max(0,step)*8,'#789a55',9);line(8,-16,12-step*11,-Math.max(0,-step)*8,'#789a55',9);ellipse(0,-28,15,20,e.color);ellipse(0,-53,19,16,e.color);ctx.fillStyle=e.color;ctx.beginPath();ctx.moveTo(-12,-62);ctx.lineTo(-29,-64);ctx.lineTo(-17,-48);ctx.fill();ctx.beginPath();ctx.moveTo(12,-62);ctx.lineTo(29,-64);ctx.lineTo(17,-48);ctx.fill();const swing=e.strike>0?Math.sin((1-e.strike/.22)*Math.PI):0;line(12,-35,23+swing*14,-24-swing*8,e.color,8);line(23+swing*14,-24-swing*8,28+swing*30,-5-swing*23,'#b99262',5);}const eyeY=e.type==='golem'?-s*1.65:e.type==='goblin'?-54:-s*.8;ellipse(-6,eyeY,2.5,3,'#293e42');ellipse(6,eyeY,2.5,3,'#293e42');ctx.fillStyle='#20394270';ctx.fillRect(-s,-s*2.2-9,s*2,4);ctx.fillStyle='#f8d780';ctx.fillRect(-s,-s*2.2-9,s*2*Math.max(0,e.hp/e.maxHp),4);ctx.restore();ctx.restore();}
function render(t){const canvas=$('canvas'),bounds=canvas.getBoundingClientRect(),height=Math.max(140,Math.round(700*bounds.height/bounds.width));if(canvas.height!==height)canvas.height=height;ctx.save();ctx.clearRect(0,0,700,height);ctx.fillStyle='#b8d6cb';ctx.fillRect(0,0,700,height);ctx.translate(0,height<350?height-272:(height-350)*.5);const sky=ctx.createLinearGradient(0,0,0,350);sky.addColorStop(0,'#b8d6cb');sky.addColorStop(1,'#e4e1b8');ctx.fillStyle=sky;ctx.fillRect(0,0,700,350);ellipse(580,65,33,33,'#fff4c7');for(let i=0;i<12;i++){const x=i*70;line(x+16,50,x+16,255,'#7caca199',14);ellipse(x+15,65+(i%3)*20,55,75,'#80aaa080');}ctx.fillStyle='#83a68b';ctx.beginPath();ctx.moveTo(0,236);ctx.quadraticCurveTo(300,196,700,231);ctx.lineTo(700,350);ctx.lineTo(0,350);ctx.fill();ctx.fillStyle='#c7bd91';ctx.beginPath();ctx.moveTo(0,249);ctx.quadraticCurveTo(350,221,700,251);ctx.lineTo(700,305);ctx.quadraticCurveTo(350,267,0,312);ctx.fill();for(let i=0;i<25;i++){const x=i*31;line(x,320+(i%4)*4,x+4,310+(i%4)*4,'#668b76',2);}if(shake>0)ctx.translate(Math.sin(t*137)*shake*.5,Math.cos(t*173)*shake*.5);
 if(game){[...game.enemies.filter(e=>!e.dead||e.deathTime>0)].sort((a,b)=>a.y-b.y).forEach(e=>enemy(e,t));for(const g of ghosts){ctx.save();ctx.globalAlpha=g.life/.16*.24;hero(g.h);ctx.restore();}hero(game.hero);}else{hero({x:350,face:1,pose:'idle',poseTime:0,stride:0});enemy({type:'slime',x:160,y:0,size:24,color:'#8de4bc',hp:32,maxHp:32},t);}
 for(const f of effects){ctx.globalAlpha=Math.min(1,f.life/f.duration);ctx.save();ctx.shadowColor=f.id==='hammer'?'#ffdc80':'#b6fff3';ctx.shadowBlur=8;ctx.strokeStyle=f.id==='hammer'?'#ffdc80':f.id==='gun'?'#eefcff':'#fff8d1';ctx.lineWidth=f.id==='hammer'?10:5;ctx.beginPath();if(f.id==='spin')ctx.ellipse(f.x,224,76,25,0,0,Math.PI*2);else if(f.id==='upper')ctx.arc(f.x+20*f.face,210,43,-Math.PI,0);else if(f.id==='hammer')ctx.ellipse(f.x,257,150*(1-f.life/f.duration),25,0,0,Math.PI*2);else{ctx.moveTo(f.x-20*f.face,218);ctx.quadraticCurveTo(f.x+30*f.face,195,f.x+83*f.face,211);ctx.moveTo(f.x-30*f.face,228);ctx.lineTo(f.x+60*f.face,222);}ctx.stroke();ctx.restore();}ctx.globalAlpha=1;
 for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*2);if(p.text){ctx.fillStyle='#fff8cc';ctx.strokeStyle='#304445';ctx.lineWidth=3;ctx.font='bold 17px sans-serif';ctx.strokeText(p.text,p.x,p.y);ctx.fillText(p.text,p.x,p.y);}else ellipse(p.x,p.y,p.size,p.size,p.color);}ctx.globalAlpha=1;ctx.restore();}
function events(){for(const e of game.events.splice(0)){if(e.type==='attack'){const duration=e.id==='hammer'?.32:.18;effects.push({...e,life:duration,duration});if(e.id!=='punch')notice(CONFIG.skills[e.id].name+'！');}if(e.type==='hit'||e.type==='hurt'){hitstop=e.type==='hit'?(e.id==='hammer'?.065:.018):.055;shake=e.type==='hit'?(e.id==='hammer'?12:4):6;particles.push({x:e.x,y:195-(e.y||0),vy:-35,vx:0,text:String(e.damage),life:.75});for(let i=0;i<7;i++)particles.push({x:e.x,y:220-(e.y||0),vx:(Math.random()-.5)*180,vy:-Math.random()*100,size:2+Math.random()*3,color:e.type==='hit'?'#ffe797':'#ffaaa0',life:.4});}if(['win','clear','defeat'].includes(e.type))save();}}
function frame(ms){const dt=Math.min((ms-last)/1000||0,.05);last=ms;if(game&&!paused&&game.run.phase==='battle'){if(hitstop>0)hitstop-=dt;else{let rest=dt*speed;while(rest>0){const step=Math.min(rest,1/60);game.update(step);rest-=step;}events();}}if(!paused){ghosts.forEach(g=>g.life-=dt);ghosts=ghosts.filter(g=>g.life>0);if(game?.run.phase==='battle'&&game.time-lastGhost>.025&&(game.hero.poseTime>0||Math.abs(game.hero.motion)>120)){ghosts.push({h:{...game.hero},life:.16});lastGhost=game.time;}particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;});particles=particles.filter(p=>p.life>0);effects.forEach(f=>f.life-=dt);effects=effects.filter(f=>f.life>0);shake=Math.max(0,shake-dt*40);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').textContent='';}}render(game?game.time:0);ui();requestAnimationFrame(frame);}
title();requestAnimationFrame(frame);
