import {Game,CONFIG,fresh} from './game.js';
const $=id=>document.getElementById(id),ctx=$('canvas').getContext('2d'),KEY='marutto-fighter-v1';
let game=null,paused=false,speed=1,particles=[],effects=[],hitstop=0,shake=0,last=0,shown='',toastTime=0,saved=null,storageOK=true;
try{saved=JSON.parse(localStorage.getItem(KEY));if(saved&&!(saved.version===1&&['battle','upgrade'].includes(saved.phase)&&Number.isInteger(saved.wave)&&saved.wave>=0&&saved.wave<3&&Number.isFinite(saved.hp)&&saved.hp>0&&saved.hp<=100&&Number.isFinite(saved.gauge)&&saved.gauge>=0&&saved.gauge<=100&&saved.skills?.punch&&Object.keys(saved.skills).every(k=>CONFIG.skills[k]&&Number.isInteger(saved.skills[k])&&saved.skills[k]>0)&&Array.isArray(saved.choices)))saved=null;}catch{saved=null;}
function save(){try{if(['battle','upgrade'].includes(game.run.phase)){saved=structuredClone(game.run);localStorage.setItem(KEY,JSON.stringify(saved));}else{saved=null;localStorage.removeItem(KEY);}}catch{storageOK=false;notice('このブラウザでは保存できません');}}
function notice(text){$('toast').textContent=text;toastTime=2;}
const descriptions={punch:'連撃ダメージが40%アップ',upper:'敵を打ち上げる。ゴーレムには耐性あり',gun:'浮いた敵へ自動追撃。アッパーと連携',spin:'敵が2体以上近づくと範囲攻撃',hammer:'ゲージ満タンで広範囲へ大打撃'};
function title(){shown='title';$('overlay').innerHTML='<div class="panel"><p class="eyebrow">A LITTLE HERO, A BIG ADVENTURE</p><h1>まるっとファイター</h1><p>小さな体で、森いっぱいの敵に挑む。<br>戦いは自動。あなたが選ぶのは、次の強さ。</p><div class="actions"><button class="primary" id="new">新しく挑戦</button>'+(saved?'<button id="resume">つづきから</button>':'')+'</div><p style="font-size:12px">全3戦 / 仮素材の試作版 / 横画面がおすすめ</p></div>';$('new').onclick=()=>start(fresh());if(saved)$('resume').onclick=()=>start(saved);}
function start(run){game=new Game(run);particles=[];effects=[];paused=false;shown='';save();ui();}
function ui(){if(!game)return;const r=game.run;$('status').hidden=false;$('pause').hidden=r.phase!=='battle';$('pause').textContent=paused?'再開':'一時停止';$('wave').textContent=`第 ${r.wave+1} 戦 / 3`;$('hp').textContent=Math.ceil(r.hp);$('hpFill').style.width=r.hp+'%';$('remaining').textContent=`敵 ${game.enemies.filter(e=>!e.dead).length} 体`;$('gauge').textContent=Math.floor(r.gauge);$('gaugeFill').style.width=r.gauge+'%';$('hint').textContent=!storageOK?'保存不可：この画面を開いたまま遊んでください':r.phase==='battle'?'戦闘は自動。赤い予兆は敵の攻撃。':'強化を選んで次の戦闘へ';
 $('skills').innerHTML=Object.entries(CONFIG.skills).map(([id,s])=>`<div class="skill ${r.skills[id]?'':'locked'}"><b>${s.icon}</b>${s.name}<small>${r.skills[id]?`Lv.${r.skills[id]} · ${game.cooldowns[id]>0?game.cooldowns[id].toFixed(1)+'秒':'準備OK'}`:'未習得'}</small></div>`).join('');
 const phase=paused?'pause':r.phase;if(phase===shown)return;shown=phase;
 if(phase==='battle')$('overlay').innerHTML='';
 else if(phase==='pause'){$('overlay').innerHTML='<div class="panel"><h2>ひとやすみ</h2><p>戦闘は停止しています。</p><button class="primary" id="continue">再開する</button></div>';$('continue').onclick=()=>{paused=false;ui();};}
 else if(phase==='upgrade'){$('overlay').innerHTML='<div class="panel"><p class="eyebrow">BATTLE COMPLETE</p><h2>次の強さを選ぼう</h2><p>HPを20回復しました。1つ選んで次の戦闘へ。</p><div class="choices">'+r.choices.map((c,i)=>`<button class="choice" data-choice="${i}"><span>${CONFIG.skills[c.id].icon}</span><strong>${CONFIG.skills[c.id].name}${c.upgrade?'＋':''}</strong><small>${c.upgrade?'ダメージが40%分アップ':descriptions[c.id]}</small></button>`).join('')+'</div></div>';document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(game.choose(Number(b.dataset.choice))){particles=[];effects=[];save();ui();}});}
 else{$('overlay').innerHTML=`<div class="panel"><p class="eyebrow">${phase==='clear'?'FOREST CLEARED':'TRY AGAIN'}</p><h1>${phase==='clear'?'森のチャンピオン！':'また挑戦しよう'}</h1><p>${phase==='clear'?'全3戦クリア！小さな英雄の大きな勝利。':`第${r.wave+1}戦で力尽きました。強化を変えて再挑戦。`}</p><button class="primary" id="retry">もう一度挑戦</button></div>`;$('retry').onclick=()=>start(fresh());}}
$('pause').onclick=()=>{paused=!paused;ui();};$('speed').onclick=()=>{speed=speed===1?2:1;$('speed').textContent=`速度 ×${speed}`;};document.addEventListener('visibilitychange',()=>{if(document.hidden&&game?.run.phase==='battle'){paused=true;ui();}});
function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
function line(x,y,x2,y2,color,width){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,y2);ctx.stroke();}
function hero(x,face,pose,t){ctx.save();ctx.translate(x,255);ctx.scale(face,1);const bounce=Math.sin(t*8)*2;const active=pose!=='idle';ellipse(0,8,24,6,'#223f4033');line(-7,-23,-14+(active?-8:0),0,'#e3ece9',11);line(7,-23,16+(active?10:0),0,'#fff',11);line(0,-48,0,-24,'#fff',16);line(-4,-44,-19,-30,'#e3ece9',10);line(5,-44,active?34:18,pose==='upper'?-78:-34,'#fff',10);ellipse(0,-65+bounce,18,19,'#fff');if(pose==='dodge')line(-30,-50,-53,-40,'#fff7',3);if(pose==='hammer'){line(20,-37,45,-86,'#eac178',7);ctx.fillStyle='#ffe29d';ctx.save();ctx.translate(47,-90);ctx.rotate(.4);ctx.fillRect(-26,-14,52,28);ctx.restore();}ctx.restore();}
function enemy(e,t){const y=255-e.y,s=e.size;ellipse(e.x,262,s*.85,5,'#1b3e3833');ctx.save();ctx.translate(e.x,y);if(e.windup>0){ctx.strokeStyle='#ff7167';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-s, s+9,0,Math.PI*2);ctx.stroke();}if(e.type==='slime'){ellipse(0,-s*.65,s,s*.7+Math.sin(t*5)*3,e.color);}else if(e.type==='boar'){ellipse(0,-s*.55,s+5,s*.65,e.color);ellipse(-s*.7,-s*.5,13,10,'#ddb199');line(-12,-7,-12,1,'#765c51',8);line(15,-7,15,1,'#765c51',8);line(-s,-s*.4,-s-7,-s*.8,'#fff5ce',4);}else if(e.type==='golem'){ctx.fillStyle=e.color;ctx.fillRect(-s*.65,-s*1.35,s*1.3,s);ctx.fillStyle='#c2cbd1';ctx.fillRect(-s*.45,-s*1.95,s*.9,s*.65);line(-s*.7,-s,-s,-s*.35,e.color,18);line(s*.7,-s,s,-s*.35,e.color,18);line(-16,-20,-19,0,'#798998',17);line(16,-20,19,0,'#798998',17);}else{line(-8,-16,-12,0,'#789a55',9);line(8,-16,12,0,'#789a55',9);ellipse(0,-28,15,20,e.color);ellipse(0,-53,19,16,e.color);ctx.fillStyle=e.color;ctx.beginPath();ctx.moveTo(-12,-62);ctx.lineTo(-29,-64);ctx.lineTo(-17,-48);ctx.fill();ctx.beginPath();ctx.moveTo(12,-62);ctx.lineTo(29,-64);ctx.lineTo(17,-48);ctx.fill();line(18,-35,26,-10,'#b99262',5);}const eyeY=e.type==='golem'?-s*1.65:e.type==='goblin'?-54:-s*.8;ellipse(-6,eyeY,2.5,3,'#293e42');ellipse(6,eyeY,2.5,3,'#293e42');ctx.fillStyle='#20394270';ctx.fillRect(-s,-s*2.2-9,s*2,4);ctx.fillStyle='#f8d780';ctx.fillRect(-s,-s*2.2-9,s*2*Math.max(0,e.hp/e.maxHp),4);ctx.restore();}
function render(t){ctx.save();ctx.clearRect(0,0,700,350);const sky=ctx.createLinearGradient(0,0,0,350);sky.addColorStop(0,'#b8d6cb');sky.addColorStop(1,'#e4e1b8');ctx.fillStyle=sky;ctx.fillRect(0,0,700,350);ellipse(580,65,33,33,'#fff4c7');for(let i=0;i<12;i++){const x=i*70;line(x+16,50,x+16,255,'#7caca199',14);ellipse(x+15,65+(i%3)*20,55,75,'#80aaa080');}ctx.fillStyle='#83a68b';ctx.beginPath();ctx.moveTo(0,236);ctx.quadraticCurveTo(300,196,700,231);ctx.lineTo(700,350);ctx.lineTo(0,350);ctx.fill();ctx.fillStyle='#c7bd91';ctx.beginPath();ctx.moveTo(0,249);ctx.quadraticCurveTo(350,221,700,251);ctx.lineTo(700,305);ctx.quadraticCurveTo(350,267,0,312);ctx.fill();for(let i=0;i<25;i++){const x=i*31;line(x,320+(i%4)*4,x+4,310+(i%4)*4,'#668b76',2);}if(shake>0)ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);
 if(game){[...game.enemies.filter(e=>!e.dead)].sort((a,b)=>a.y-b.y).forEach(e=>enemy(e,t));hero(game.hero.x,game.hero.face,game.hero.poseTime>0?game.hero.pose:'idle',t);}else{hero(350,1,'idle',t);enemy({type:'slime',x:160,y:0,size:24,color:'#8de4bc',hp:32,maxHp:32},t);}
 for(const f of effects){ctx.globalAlpha=Math.min(1,f.life*3);ctx.strokeStyle=f.id==='hammer'?'#ffdc80':f.id==='gun'?'#eefcff':'#fff8d1';ctx.lineWidth=f.id==='hammer'?10:5;ctx.beginPath();if(f.id==='spin')ctx.ellipse(f.x,224,76,25,0,0,Math.PI*2);else if(f.id==='upper')ctx.arc(f.x+20*f.face,210,43,-Math.PI,0);else if(f.id==='hammer')ctx.ellipse(f.x,257,150*(1-f.life/.45),25,0,0,Math.PI*2);else{ctx.moveTo(f.x,218);ctx.lineTo(f.x+90*f.face,195);}ctx.stroke();}ctx.globalAlpha=1;
 for(const p of particles){ctx.globalAlpha=Math.min(1,p.life*2);if(p.text){ctx.fillStyle='#fff8cc';ctx.strokeStyle='#304445';ctx.lineWidth=3;ctx.font='bold 17px sans-serif';ctx.strokeText(p.text,p.x,p.y);ctx.fillText(p.text,p.x,p.y);}else ellipse(p.x,p.y,p.size,p.size,p.color);}ctx.globalAlpha=1;ctx.restore();}
function events(){for(const e of game.events.splice(0)){if(e.type==='attack'){effects.push({...e,life:.45});if(e.id!=='punch')notice(CONFIG.skills[e.id].name+'！');}if(e.type==='hit'||e.type==='hurt'){hitstop=e.type==='hit'?.045:.07;shake=e.type==='hit'?5:8;particles.push({x:e.x,y:195-(e.y||0),vy:-35,vx:0,text:String(e.damage),life:.75});for(let i=0;i<7;i++)particles.push({x:e.x,y:220-(e.y||0),vx:(Math.random()-.5)*180,vy:-Math.random()*100,size:2+Math.random()*3,color:e.type==='hit'?'#ffe797':'#ffaaa0',life:.4});}if(['win','clear','defeat'].includes(e.type))save();}}
function frame(ms){const dt=Math.min((ms-last)/1000||0,.05);last=ms;if(game&&!paused&&game.run.phase==='battle'){if(hitstop>0)hitstop-=dt;else{let rest=dt*speed;while(rest>0){const step=Math.min(rest,1/60);game.update(step);rest-=step;}events();}}if(!paused){particles.forEach(p=>{p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;});particles=particles.filter(p=>p.life>0);effects.forEach(f=>f.life-=dt);effects=effects.filter(f=>f.life>0);shake=Math.max(0,shake-dt*40);if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').textContent='';}}render(ms/1000);ui();requestAnimationFrame(frame);}
title();requestAnimationFrame(frame);
