import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,fresh,CONFIG} from '../game.js';
import {DURATIONS,CONTACT} from '../motion.js';
function finishWave(g){for(const e of g.enemies)e.dead=true;g.update(.02);}
test('three battles, one-time recovery/reward, clear and restart',()=>{const g=new Game();g.run.hp=55;finishWave(g);assert.equal(g.run.hp,75);assert.equal(g.run.phase,'upgrade');g.update(1);assert.equal(g.run.hp,75);assert.deepEqual(g.run.choices.map(c=>c.id),['upper','spin','hammer']);assert.ok(g.choose(0));assert.equal(g.run.skills.upper,1);assert.equal(g.run.hp,75);assert.equal(g.choose(0),false);finishWave(g);assert.equal(g.run.wave,2);assert.equal(g.run.choices[0].id,'gun');g.choose(0);finishWave(g);assert.equal(g.run.phase,'clear');assert.deepEqual(new Game().run,fresh());});
test('save restores battle starting state and upgrade decision',()=>{const g=new Game();const checkpoint=structuredClone(g.run);g.update(3);g.run.hp=2;const resumed=new Game(checkpoint);assert.equal(resumed.run.hp,100);assert.equal(resumed.enemies[0].hp,32);finishWave(resumed);const upgrade=new Game(resumed.run);assert.equal(upgrade.run.phase,'upgrade');assert.ok(upgrade.choose(1));assert.equal(upgrade.run.skills.spin,1);});
function advance(g,seconds){for(let t=0;t<seconds;t+=1/120)g.update(1/120);}
test('upper prepares before contact, launches then chains to airborne gun',()=>{const g=new Game();g.run.skills={punch:1,upper:1,gun:1};g.enemies.forEach((e,i)=>{e.dead=i!==0;e.x=360;});g.enemies[0].hp=150;g.update(.016);assert.equal(g.enemies[0].hp,150);assert.equal(g.enemies[0].vy,0);advance(g,CONTACT.upper+.01);assert.ok(g.enemies[0].vy>0);assert.equal(g.enemies[0].hp,125);advance(g,DURATIONS.upper+.2);assert.ok(g.events.some(e=>e.type==='attack'&&e.id==='gun'));const rock={...CONFIG.enemies.golem,type:'golem',x:g.hero.x,y:0,vy:0,vx:0};g.impact({id:'upper',targets:[rock],face:1,combo:0});assert.equal(rock.vy,0);assert.equal(rock.hp,185);});
test('spin and hammer connect after their windup; empty hammer preserves gauge',()=>{const g=new Game();g.run.skills={punch:1,spin:1,hammer:1};g.enemies.forEach(e=>{e.x=360;e.hp=200;});g.update(.016);assert.equal(g.hero.pose,'spin');assert.ok(!g.events.some(e=>e.type==='hit'));advance(g,CONTACT.spin+.01);assert.ok(g.events.some(e=>e.type==='attack'&&e.id==='spin'));g.run.gauge=100;advance(g,DURATIONS.spin-CONTACT.spin+.02);assert.equal(g.hero.pose,'hammer');assert.equal(g.run.gauge,100);advance(g,CONTACT.hammer+.02);assert.ok(g.events.some(e=>e.type==='attack'&&e.id==='hammer'));assert.equal(g.run.gauge,0);g.run.hp=0;g.update(.016);assert.equal(g.run.phase,'defeat');const empty=new Game();empty.run.skills.hammer=1;empty.run.gauge=100;empty.enemies.forEach(e=>e.dead=true);empty.update(.016);assert.equal(empty.run.gauge,100);});
test('attack can miss and cannot be replaced during recovery',()=>{const g=new Game();const target=g.enemies[0];target.x=360;const hp=target.hp;assert.ok(g.attack('punch',[target]));assert.equal(g.attack('punch',[target]),false);target.x=650;advance(g,CONTACT.punch+.015);assert.equal(target.hp,hp);assert.equal(g.combo,1);assert.equal(g.attack('punch',[target]),false);});
test('dodge travels continuously and death retains a brief physical exit',()=>{const g=new Game();g.enemies.forEach((e,i)=>{e.dead=i!==0;});const e=g.enemies[0];e.x=390;e.windup=.1;const x=g.hero.x;g.update(.01);assert.equal(g.hero.x,x);g.update(.01);assert.ok(g.hero.x<x&&g.hero.x>x-65);const hp=g.run.hp;advance(g,.35);assert.equal(g.run.hp,hp);e.x=g.hero.x+20;e.hp=1;g.impact({id:'punch',targets:[e],face:1,combo:0});assert.equal(e.dead,true);assert.ok(e.deathTime>0);assert.ok(e.vy>0);});
test('natural simulation completes three waves with every first reward route',()=>{for(let route=0;route<3;route++){const g=new Game();let ticks=0;while(g.run.phase!=='clear'&&g.run.phase!=='defeat'&&ticks++<18000){if(g.run.phase==='upgrade')g.choose(g.run.wave===1?route:0);g.update(1/60);}assert.equal(g.run.phase,'clear',`route ${route}, hp ${g.run.hp}`);}});
test('rapid combo connects three strikes within one second with bounded steps',()=>{const g=new Game();const e=g.enemies[0];g.enemies.forEach((enemy,i)=>{enemy.dead=i!==0;});e.x=395;e.hp=1000;for(let i=0;i<120;i++){g.update(1/120);assert.ok(g.hero.x>=50&&g.hero.x<=650);}assert.ok(g.events.filter(event=>event.type==='attack'&&event.id==='punch').length>=3);assert.ok(g.enemies[0].hp<1000);});
