import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,fresh,CONFIG} from '../game.js';
function finishWave(g){for(const e of g.enemies)e.dead=true;g.update(.02);}
test('three battles, one-time recovery/reward, clear and restart',()=>{const g=new Game();g.run.hp=55;finishWave(g);assert.equal(g.run.hp,75);assert.equal(g.run.phase,'upgrade');g.update(1);assert.equal(g.run.hp,75);assert.deepEqual(g.run.choices.map(c=>c.id),['upper','spin','hammer']);assert.ok(g.choose(0));assert.equal(g.run.skills.upper,1);assert.equal(g.run.hp,75);assert.equal(g.choose(0),false);finishWave(g);assert.equal(g.run.wave,2);assert.equal(g.run.choices[0].id,'gun');g.choose(0);finishWave(g);assert.equal(g.run.phase,'clear');assert.deepEqual(new Game().run,fresh());});
test('save restores battle starting state and upgrade decision',()=>{const g=new Game();const checkpoint=structuredClone(g.run);g.update(3);g.run.hp=2;const resumed=new Game(checkpoint);assert.equal(resumed.run.hp,100);assert.equal(resumed.enemies[0].hp,32);finishWave(resumed);const upgrade=new Game(resumed.run);assert.equal(upgrade.run.phase,'upgrade');assert.ok(upgrade.choose(1));assert.equal(upgrade.run.skills.spin,1);});
test('upper launches, aerial gun follows; golem resists launch',()=>{const g=new Game();g.run.skills={punch:1,upper:1,gun:1};g.enemies.forEach((e,i)=>{e.dead=i!==0;e.x=360;});g.enemies[0].hp=150;g.update(.016);assert.ok(g.enemies[0].vy>0);for(let i=0;i<20;i++)g.update(.016);assert.ok(g.events.some(e=>e.type==='attack'&&e.id==='gun'));const rock={...CONFIG.enemies.golem,type:'golem',x:350,y:0,vy:0,vx:0};g.attack('upper',[rock]);assert.equal(rock.vy,0);});
test('spin hits crowds, hammer waits for enemies, death leads to defeat',()=>{const g=new Game();g.run.skills={punch:1,spin:1,hammer:1};g.enemies.forEach(e=>{e.x=360;e.hp=200;});g.update(.016);assert.ok(g.events.some(e=>e.id==='spin'));g.run.gauge=100;g.update(.016);assert.ok(g.events.some(e=>e.id==='hammer'));assert.equal(g.run.gauge,0);g.run.hp=0;g.update(.016);assert.equal(g.run.phase,'defeat');const empty=new Game();empty.run.skills.hammer=1;empty.run.gauge=100;empty.enemies.forEach(e=>e.dead=true);empty.update(.016);assert.equal(empty.run.gauge,100);});
test('natural simulation completes three waves with every first reward route',()=>{for(let route=0;route<3;route++){const g=new Game();let ticks=0;while(g.run.phase!=='clear'&&g.run.phase!=='defeat'&&ticks++<18000){if(g.run.phase==='upgrade')g.choose(g.run.wave===1?route:0);g.update(1/60);}assert.equal(g.run.phase,'clear',`route ${route}, hp ${g.run.hp}`);}});
